[package]
name = "brc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
memmap2 = { version = "0.9.9" }

[profile.profiled]
inherits = "release"
opt-level = 3
debug = 1
strip = "none"
force-frame-pointers = true
