[package]
name = "brc"
version = "0.1.0"
edition = "2024"

[dependencies]
atoi = "2.0.0"
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
memmap2 = { version = "0.9.9" }

[profile.profiled]
inherits = "release"
opt-level = 3
debug = 2
strip = "none"
